package com.example.ecommerceapp.ui.product.Screen


import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.compose.runtime.*

object AppLanguage {

    enum class AppLanguage(val label: String) {
        EN("English"),
        FR("Français"),
        AR("العربية")
    }

    var defaultLanguage = AppLanguage.EN

    @Composable
    fun rememberLanguage(): Instance {
        var current by remember { mutableStateOf(defaultLanguage) }
        return Instance(current) { current = it }
    }


    class Instance(
        val current: AppLanguage,
        val onChange: (AppLanguage) -> Unit
    ) {
        private val texts = mapOf(
            AppLanguage.EN to mapOf(
                "register" to "Register",
                "login" to "Login",
                "first_name" to "First Name",
                "last_name" to "Last Name",
                "email" to "Email",
                "password" to "Password",
                "phone" to "Phone Number",
                "already_registered" to "You have an account? Login",
                "invalid_email" to "Please enter a valid email address.",
                "password_too_short" to "Password must be at least 8 characters.",
                "empty_fields" to "Please fill in all fields.",
                "email_used" to "This email is already registered.",
                "accept_terms" to "By creating an account, you agree to our",
                "privacy_policy" to "Privacy Policy",
                "invalid_credentials" to "Invalid email or password.",
                "no_account_register" to "Don't have an account? Register",
                "search" to "Search...",
                "filters" to "Filters",
                "skin_care" to "Skin Care >",
                "all" to "All",
                "offers" to "Offers products",
                "Priceh" to "Price ↑",
                "Priceb" to "Price ↓",
                "Sort" to "Sort with Price",
                "Low" to "Low to High",
                "High" to "High to Low",
                "Without" to "Without",
                "Ending Soon" to "Ending Soon",
                "Products for you my lady" to "Products for you my lady",
                "Featured Products >" to "Featured Products >",
                "The right skin care routine" to "The right skin care routine",
                "MORE OF OUR SOCIALS" to "MORE OF OUR SOCIALS",
                "My Fvorite >" to "My Fvorite >",
                "My Cart >" to "My Cart >",
                "Your cart is empty." to "Your cart is empty.",
                "Checkout" to "Checkout",
                "Product Details >" to "Product Details >",
                "Add to Cart" to "Add to Cart",
                "Your rating >" to "Your rating >",
                "You Might Like >" to "You Might Like >",
                "Ctegory >" to "Ctegory >",
                "Please enter a valid email address" to "Please enter a valid email address",
                "Email me with news and offers" to "Email me with news and offers",
                "Contact" to "Contact",
                "Delivery" to "Delivery",
                "Country/Region" to "Country/Region",
                "Address" to "Address",
                "Postal Code" to "Postal Code",
                "Select the gift and the package you want" to "Select the gift and the package you want",
                "Gift and Package" to "Gift and Package",
                "Shipping Method" to "Shipping Method",
                "Enter your shipping address to view available shipping methods." to "Enter your shipping address to view available shipping methods.",
                "Payment" to "Payment",
                "Card number" to "Card number",
                "Expiration date (MM / YY)" to "Expiration date (MM / YY)",
                "Enter a valid expiry date (MM / YY)" to "Enter a valid expiry date (MM / YY)",
                "Security code" to "Security code",
                "Name on card" to "Name on card",
                "Use shipping address as billing address" to "Use shipping address as billing address",
                "Order Summary" to "Order Summary",
                "Your Package and your gift" to "Your Package and your gift",
                "Your products" to "Your products",
                "Delivery: $5.50" to "Delivery: $5.50",
                "Pay" to "Pay",
                "Tracking >" to "Tracking >",
                "Your Informations:" to "Your Informations:",
                "Order Tracking" to "Order Tracking",
                "Checkout >" to "Checkout >",
                "Name: " to "Name: ",
                "Country: " to "Country: ",
                "Postal Code: " to "Postal Code: ",
                "Address: " to "Address: ",
                "Email: " to "Email: ",
                "Your order will arrive within 48 hours" to "Your order will arrive within 48 hours",
                "👥 Users" to "👥 Users",
                "🛍️ Products" to "🛍️ Products",
                "No users registered yet." to "No users registered yet.",
                "No products available." to "No products available.",
                "This account has been blocked and cannot log in." to "This account has been blocked and cannot log in.",
                "This account has been blocked and cannot register again." to "This account has been blocked and cannot register again.",
                "Delete" to "Delete",
                "Name:  " to "Name:  ",
                "Phone: " to "Phone: ",
                "Category:  " to "Category:  ",
                "Stock:  " to "Stock:  ",
                "Brand:  " to "Brand:  ",
                "Admin page >" to "Admin page >",
                "Details" to "Details",
                "Orders for: " to "Orders for: ",

                ),

            AppLanguage.FR to mapOf(
                "register" to "S'inscrire",
                "login" to "Se connecter",
                "first_name" to "Prénom",
                "last_name" to "Nom de famille",
                "email" to "Email",
                "password" to "Mot de passe",
                "phone" to "Numéro de téléphone",
                "already_registered" to "Vous avez déjà un compte ? Connectez-vous",
                "invalid_email" to "Veuillez entrer une adresse e-mail valide.",
                "password_too_short" to "Le mot de passe doit comporter au moins 8 caractères.",
                "empty_fields" to "Veuillez remplir tous les champs.",
                "email_used" to "Cet e-mail est déjà enregistré.",
                "accept_terms" to "En créant un compte, vous acceptez notre",
                "privacy_policy" to "Politique de confidentialité",
                "invalid_credentials" to "Email ou mot de passe invalide.",
                "no_account_register" to "Vous n'avez pas de compte ? S'inscrire",
                "search" to "Recherche...",
                "filters" to "Filtres",
                "skin_care" to "Soins de la peau >",
                "all" to "Tous",
                "offers" to "Produits en promotion",
                "Priceh" to "Prix ↑",
                "Priceb" to "Prix ↓",
                "Sort" to "Trier par prix",
                "Low" to "Du moins cher au plus cher",
                "High" to "Du plus cher au moins cher",
                "Products for you my lady" to "Produits pour vous, madame",
                "Featured Products >" to "Produits en vedette >",
                "The right skin care routine" to "La bonne routine de soins de la peau",
                "MORE OF OUR SOCIALS" to "PLUS DE NOS RÉSEAUX SOCIAUX",
                "My Fvorite >" to "Mes favoris >",
                "My Cart >" to "Mon panier >",
                "Your cart is empty." to "Votre panier est vide.",
                "Checkout" to "Paiement",
                "Product Details >" to "Détails du produit >",
                "Add to Cart" to "Ajouter au panier",
                "Your rating >" to "Votre évaluation >",
                "You Might Like >" to "Vous pourriez aimer >",
                "Ctegory >" to "Catégorie >",
                "Please enter a valid email address" to "Veuillez entrer une adresse e-mail valide",
                "Email me with news and offers" to "Envoyez-moi des offres et actualités par e-mail",
                "Contact" to "Contact",
                "Delivery" to "Livraison",
                "Country/Region" to "Pays/Région",
                "Address" to "Adresse",
                "Postal Code" to "Code postal",
                "Select the gift and the package you want" to "Sélectionnez le cadeau et l'emballage que vous souhaitez",
                "Gift and Package" to "Cadeau et emballage",
                "Shipping Method" to "Mode de livraison",
                "Enter your shipping address to view available shipping methods." to "Entrez votre adresse pour voir les méthodes de livraison disponibles.",
                "Payment" to "Paiement",
                "Card number" to "Numéro de carte",
                "Expiration date (MM / YY)" to "Date d'expiration (MM / AA)",
                "Enter a valid expiry date (MM / YY)" to "Entrez une date d'expiration valide (MM / AA)",
                "Security code" to "Code de sécurité",
                "Name on card" to "Nom sur la carte",
                "Use shipping address as billing address" to "Utiliser l'adresse de livraison comme adresse de facturation",
                "Order Summary" to "Résumé de la commande",
                "Your products" to "Vos produits",
                "Delivery: $5.50" to "Livraison : 5,50 $",
                "Pay" to "Payer",
                "Without" to "Sans",
                "Ending Soon" to "Se termine bientôt",
                "Your Package and your gift" to "Votre colis et votre cadeau",
                "Tracking >" to "Suivi >",
                "Your Informations:" to "Vos informations :",
                "Order Tracking" to "Suivi de commande",
                "Checkout >" to "Paiement >",
                "Name: " to "Nom :",
                "Country: " to "Pays :",
                "Postal Code: " to "Code postal :",
                "Address: " to "Adresse :",
                "Email: " to "Email: ",
                "Your order will arrive within 48 hours" to "Votre commande arrivera sous 48 heures",
                "👥 Users" to "👥 Utilisateurs",
                 "🛍️ Products" to "🛍️ Produits",
                "No users registered yet." to "Aucun utilisateur enregistré pour le moment.",
                "No products available." to "Aucun produit disponible.",
                "This account has been blocked and cannot log in." to "Ce compte a été bloqué et ne peut pas se connecter.",
                "This account has been blocked and cannot register again." to "Ce compte a été bloqué et ne peut pas s'enregistrer à nouveau.",
                "Delete" to "Supprimer",
                "Name:  " to "Nom :  ",
                "Phone: " to "Téléphone: ",
                "Category:  " to "Catégorie :  ",
                "Stock:  " to "Stock :  ",
                "Brand:  " to "Marque :  ",
                "Admin page >" to "Page Admin >"


            ),
            AppLanguage.AR to mapOf(
                "register" to "التسجيل",
                "login" to "تسجيل الدخول",
                "first_name" to "الاسم الأول",
                "last_name" to "اسم العائلة",
                "email" to "البريد الإلكتروني",
                "password" to "كلمة المرور",
                "phone" to "رقم الهاتف",
                "already_registered" to "لديك حساب؟ سجل الدخول",
                "invalid_email" to "يرجى إدخال بريد إلكتروني صالح.",
                "password_too_short" to "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
                "empty_fields" to "يرجى ملء جميع الحقول.",
                "email_used" to "هذا البريد الإلكتروني مسجل بالفعل.",
                "accept_terms" to "بإنشاء حساب، فإنك توافق على",
                "privacy_policy" to "سياسة الخصوصية",
                "invalid_credentials" to "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
                "no_account_register" to "ليس لديك حساب؟ سجل الآن",
                "search" to "ابحث...",
                "filters" to "الفلاتر",
                "skin_care" to "العناية بالبشرة >",
                "all" to "الكل",
                "offers" to "منتجات بعروض",
                "Priceh" to "السعر ↑",
                "Priceb" to "السعر ↓",
                "Sort" to "ترتيب حسب السعر",
                "Low" to "من الأقل للأعلى",
                "High" to "من الأعلى للأقل",
                "Ending Soon" to "سينتهي قريبًا",
                "Products for you my lady" to "منتجات لك سيدتي",
                "Featured Products >" to "منتجات مميزة >",
                "The right skin care routine" to "روتين العناية بالبشرة الصحيح",
                "MORE OF OUR SOCIALS" to "المزيد من شبكاتنا",
                "My Fvorite >" to "مفضلاتي >",
                "My Cart >" to "سلتي >",
                "Your cart is empty." to "سلتك فارغة.",
                "Checkout" to "إتمام الطلب",
                "Product Details >" to "تفاصيل المنتج >",
                "Add to Cart" to "أضف إلى السلة",
                "Your rating >" to "تقييمك >",
                "You Might Like >" to "قد يعجبك أيضًا >",
                "Ctegory >" to "الفئة >",
                "Please enter a valid email address" to "يرجى إدخال بريد إلكتروني صحيح",
                "Email me with news and offers" to "أرسل لي العروض والأخبار على بريدي",
                "Contact" to "الاتصال",
                "Delivery" to "التوصيل",
                "Country/Region" to "الدولة/المنطقة",
                "Address" to "العنوان",
                "Postal Code" to "الرمز البريدي",
                "Select the gift and the package you want" to "اختر الهدية والتغليف الذي تريده",
                "Gift and Package" to "الهدية والتغليف",
                "Shipping Method" to "طريقة الشحن",
                "Enter your shipping address to view available shipping methods." to "أدخل عنوان الشحن لعرض طرق التوصيل المتاحة.",
                "Payment" to "الدفع",
                "Card number" to "رقم البطاقة",
                "Expiration date (MM / YY)" to "تاريخ الانتهاء (شهر / سنة)",
                "Enter a valid expiry date (MM / YY)" to "أدخل تاريخ انتهاء صالح (شهر / سنة)",
                "Security code" to "رمز الأمان",
                "Name on card" to "الاسم على البطاقة",
                "Use shipping address as billing address" to "استخدم عنوان الشحن كعنوان الفوترة",
                "Order Summary" to "ملخص الطلب",
                "Your Package and your gift" to "تغليفك وهديةك",
                "Your products" to "منتجاتك",
                "Delivery: $5.50" to "التوصيل: 5.50 دولار",
                "Pay" to "ادفع",
                "Tracking >" to "تتبع >",
                "Your Informations:" to "معلوماتك:",
                "Order Tracking" to "تتبع الطلب",
                "Checkout >" to "الدفع >",
                "Name: " to "الاسم: ",
                "Country: " to "الدولة: ",
                "Postal Code: " to "الرمز البريدي: ",
                "Address: " to "العنوان: ",
                "Your order will arrive within 48 hours" to "سيصل طلبك خلال 48 ساعة",
                "👥 Users" to "👥 المستخدمون",
                "🛍️ Products" to "🛍️ المنتجات",
                "No users registered yet."  to "لم يتم تسجيل أي مستخدم بعد.",
                "No products available."  to "لا توجد منتجات متاحة.",
                "This account has been blocked and cannot log in."  to "تم حظر هذا الحساب ولا يمكنه تسجيل الدخول.",
                "This account has been blocked and cannot register again."  to "تم حظر هذا الحساب ولا يمكنه التسجيل مرة أخرى.",
                "Delete" to "حذف",
                "Name:  " to "الاسم:  ",
                "Phone: " to "الهاتف: ",
                "Category:  " to "الفئة:  ",
                "Stock:  " to "المخزون:  ",
                "Brand:  " to "العلامة التجارية:  ",
                "Admin page >" to "صفحة المدير >",
            )

        )
        fun get(key: String): String = texts[current]?.get(key)?:key

    }
}

